In [1]:
from pandas import *

pd = [1,3,4,5]

print(Series(pd, index=['a','b','c','d'], dtype="float", name= "python"))
print(Series(pd[1]))

a    1.0
b    3.0
c    4.0
d    5.0
Name: python, dtype: float64
0    3
dtype: int64

In [2]:
import pandas as pd

dic = {
    "name" : ['python', 'java', 'c', 'javascript'],
    "por" : [12, 13, 14, 15],
    "rank" : [1,4,3,2]


}

var1 = pd.Series(dic)

print(var1)

name    [python, java, c, javascript]
por                  [12, 13, 14, 15]
rank                     [1, 4, 3, 2]
dtype: object

In [3]:
s = pd.Series(12, index=['a', 'b','c'])

print(s)
print(type(s))

a    12
b    12
c    12
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
import pandas as pd
s1 = [1,2,3,4,5]
s2 = [3,4,5]

var1=pd.Series(s1, index=['a','b','c','d','e'])
var2=pd.Series(s2, index=['a', 'b', 'c'])
print(var1+var2)

a    4.0
b    6.0
c    8.0
d    NaN
e    NaN
dtype: float64

DataFrame

In [5]:
import pandas as pd   # usin list 

s1 = [1,2,3,4,5]
var1=pd.DataFrame(s1)
print(var1)
print(type(var1))

   0
0  1
1  2
2  3
3  4
4  5
<class 'pandas.core.frame.DataFrame'>

Using Dictionaries.....

In [6]:
import pandas as pd
dic = {
    "name" : ["rahul", "sohan", "rohan"], 
    "age" : [12,15,16],
    "class" : [6,8,12]

}

var1=pd.DataFrame(dic, index=['a','b','c'], columns=['name','class'])
print(var1)
print(var1["name"][2])

    name  class
a  rahul      6
b  sohan      8
c  rohan     12
rohan

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\1896856254.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var1["name"][2])

In [7]:
import pandas as pd

lis1 = [[1,2,3,4,5],[5,6,7,8,9]]
var1 = pd.DataFrame(lis1)
print(var1)

   0  1  2  3  4
0  1  2  3  4  5
1  5  6  7  8  9

Using two Series, the dataframe is created

In [8]:
sd={"s":pd.Series([1,2,3,4]),
    "d":pd.Series([4,5,6,7])
}
var1=pd.DataFrame(sd)
print(var1)

   s  d
0  1  4
1  2  5
2  3  6
3  4  7

Arithmatic operations on the DataFrame

In [9]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7]})

sd1["C"]=sd1["A"]+sd1["B"]

sd1["D"]=sd1["A"]-sd1["B"]

sd1["E"]=sd1["A"]*sd1["B"]

sd1["F"]=sd1["A"]/sd1["B"]

sd1["G"]=sd1["A"]%sd1["B"]
print(sd1)

   A  B   C  D   E         F  G
0  1  3   4 -2   3  0.333333  1
1  2  4   6 -2   8  0.500000  2
2  3  6   9 -3  18  0.500000  3
3  4  7  11 -3  28  0.571429  4

Logical operations on the DataFrame

In [10]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7]})
sd1["python"]=sd1["A"]<=2
sd1["python_1"]=sd1["B"]<=2
print(sd1)

   A  B  python  python_1
0  1  3    True     False
1  2  4    True     False
2  3  6   False     False
3  4  7   False     False

In [11]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7]}) #insert data in the DataFrame
sd1.insert(1,"python",sd1["A"])
print(sd1)

   A  python  B
0  1       1  3
1  2       2  4
2  3       3  6
3  4       4  7

Copying Data

In [12]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7]})
sd1["python"]=sd1["A"][:3]
print(sd1)

   A  B  python
0  1  3     1.0
1  2  4     2.0
2  3  6     3.0
3  4  7     NaN

Delete Data From DataFrame

In [13]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7], "C":[8,9,10,11]})

var1=sd1.pop("A")
print(var1)
print(sd1)

0    1
1    2
2    3
3    4
Name: A, dtype: int64
   B   C
0  3   8
1  4   9
2  6  10
3  7  11

In [14]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7]})
del sd1["A"]
print(sd1)

   B
0  3
1  4
2  6
3  7

Write csv file

In [15]:
sd1=pd.DataFrame({"A":[1,2,3,4], "B":[3,4,6,7]})
sd1.to_csv("text.csv", index=False, header=['1','2'])
sd1

   A  B
0  1  3
1  2  4
2  3  6
3  4  7

In [16]:
# Here get the number of row for example: nrows = 2 (2 rows are in output)
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv", nrows=2)
print(csv_1)

  Employee_ID           Job_Title    Industry Country Education_Level  \
0  AIJ-100000       Data Engineer  Healthcare   Japan             PhD
1  AIJ-100001  Healthcare Analyst      Retail      UK        Bachelor

   Years_Experience  AI_Replacement_Risk  Future_Demand_Score  \
0                 1                 0.25                 0.78
1                24                 0.73                 0.33

  Remote_Work_Possibility  Average_Salary_USD  \
0                     Yes              207392
1                      No              140785

                                     Required_Skills Automation_Level  \
0               Python, Communication, Deep Learning              Low
1  Deep Learning, Azure, Communication, TensorFlo...              Low

   Job_Growth_2030  Work_Hours_Per_Week Company_Size AI_Tool_Usage  \
0                3                   37   Enterprise          High
1               -5                   42      Startup      Moderate

   Performance_Score Upskilling_Needed  Job_Satisfaction Hiring_Trend_2026
0               2.08               Yes              3.86           Growing
1               4.54                No              4.23           Growing

In [17]:
# get the number of columns
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv", usecols=[1,2])
print(csv_1)

                  Job_Title    Industry
0             Data Engineer  Healthcare
1        Healthcare Analyst      Retail
2             HR Specialist   Education
3     Cybersecurity Analyst  Government
4        Healthcare Analyst   Education
...                     ...         ...
2995         Data Scientist   Education
2996          Data Engineer  Healthcare
2997        DevOps Engineer      Energy
2998         Data Scientist  Government
2999          HR Specialist      Retail

[3000 rows x 2 columns]

In [18]:
# it is skip the row 
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv", skiprows=[0])
print(csv_1)

      AIJ-100000              Data Engineer  Healthcare      Japan  \
0     AIJ-100001         Healthcare Analyst      Retail         UK
1     AIJ-100002              HR Specialist   Education     Canada
2     AIJ-100003      Cybersecurity Analyst  Government         UK
3     AIJ-100004         Healthcare Analyst   Education        UAE
4     AIJ-100005  Machine Learning Engineer      Energy      Japan
...          ...                        ...         ...        ...
2994  AIJ-102995             Data Scientist   Education      India
2995  AIJ-102996              Data Engineer  Healthcare        UAE
2996  AIJ-102997            DevOps Engineer      Energy   Pakistan
2997  AIJ-102998             Data Scientist  Government  Australia
2998  AIJ-102999              HR Specialist      Retail    Germany

              PhD   1  0.25  0.78     Yes  207392  \
0        Bachelor  24  0.73  0.33      No  140785
1     High School  21  0.80  0.69     Yes  124800
2        Bachelor   5  0.29  0.94      No  199878
3             PhD  20  0.11  0.92      No  178682
4     High School  12  0.73  0.88      No   70066
...           ...  ..   ...   ...     ...     ...
2994     Bachelor   0  0.62  0.27  Hybrid  202565
2995          PhD   4  0.52  0.57     Yes   37215
2996  High School   7  0.72  0.70      No   55179
2997     Bachelor  19  0.82  0.76  Hybrid  125291
2998       Master   9  0.68  0.44      No  152792

                   Python, Communication, Deep Learning     Low   3  37  \
0     Deep Learning, Azure, Communication, TensorFlo...     Low  -5  42
1     Kubernetes, Cloud Computing, TensorFlow, SQL, ...  Medium  -5  57
2     Excel, Kubernetes, Prompt Engineering, Leadership  Medium   7  59
3            SQL, Leadership, TensorFlow, Cybersecurity     Low   6  34
4     Excel, Deep Learning, Cybersecurity, Communica...    High  19  46
...                                                 ...     ...  ..  ..
2994  Azure, Project Management, Cloud Computing, Cy...  Medium  36  59
2995                     Communication, PyTorch, Docker     Low  17  45
2996                  TensorFlow, Excel, Python, Docker  Medium  34  35
2997      Cybersecurity, Cloud Computing, Deep Learning  Medium  21  47
2998           Kubernetes, Cybersecurity, Communication     Low  32  44

      Enterprise      High  2.08 Yes.1  3.86    Growing
0        Startup  Moderate  4.54    No  4.23    Growing
1        Startup       Low  3.14    No  3.54     Stable
2     Enterprise      High  3.67    No  4.37  Declining
3        Startup      High  3.68    No  3.99     Stable
4         Medium      High  4.58   Yes  3.72  Declining
...          ...       ...   ...   ...   ...        ...
2994  Enterprise  Moderate  4.54   Yes  1.27     Stable
2995     Startup       Low  2.71    No  2.56     Stable
2996     Startup       Low  4.88   Yes  3.17  Declining
2997     Startup  Moderate  3.59   Yes  3.78     Stable
2998      Medium  Moderate  3.29    No  1.36    Growing

[2999 rows x 20 columns]

In [19]:
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv", index_col="Job_Title")
print(csv_1)

                      Employee_ID    Industry    Country Education_Level  \
Job_Title
Data Engineer          AIJ-100000  Healthcare      Japan             PhD
Healthcare Analyst     AIJ-100001      Retail         UK        Bachelor
HR Specialist          AIJ-100002   Education     Canada     High School
Cybersecurity Analyst  AIJ-100003  Government         UK        Bachelor
Healthcare Analyst     AIJ-100004   Education        UAE             PhD
...                           ...         ...        ...             ...
Data Scientist         AIJ-102995   Education      India        Bachelor
Data Engineer          AIJ-102996  Healthcare        UAE             PhD
DevOps Engineer        AIJ-102997      Energy   Pakistan     High School
Data Scientist         AIJ-102998  Government  Australia        Bachelor
HR Specialist          AIJ-102999      Retail    Germany          Master

                       Years_Experience  AI_Replacement_Risk  \
Job_Title
Data Engineer                         1                 0.25
Healthcare Analyst                   24                 0.73
HR Specialist                        21                 0.80
Cybersecurity Analyst                 5                 0.29
Healthcare Analyst                   20                 0.11
...                                 ...                  ...
Data Scientist                        0                 0.62
Data Engineer                         4                 0.52
DevOps Engineer                       7                 0.72
Data Scientist                       19                 0.82
HR Specialist                         9                 0.68

                       Future_Demand_Score Remote_Work_Possibility  \
Job_Title
Data Engineer                         0.78                     Yes
Healthcare Analyst                    0.33                      No
HR Specialist                         0.69                     Yes
Cybersecurity Analyst                 0.94                      No
Healthcare Analyst                    0.92                      No
...                                    ...                     ...
Data Scientist                        0.27                  Hybrid
Data Engineer                         0.57                     Yes
DevOps Engineer                       0.70                      No
Data Scientist                        0.76                  Hybrid
HR Specialist                         0.44                      No

                       Average_Salary_USD  \
Job_Title
Data Engineer                      207392
Healthcare Analyst                 140785
HR Specialist                      124800
Cybersecurity Analyst              199878
Healthcare Analyst                 178682
...                                   ...
Data Scientist                     202565
Data Engineer                       37215
DevOps Engineer                     55179
Data Scientist                     125291
HR Specialist                      152792

                                                         Required_Skills  \
Job_Title
Data Engineer                       Python, Communication, Deep Learning
Healthcare Analyst     Deep Learning, Azure, Communication, TensorFlo...
HR Specialist          Kubernetes, Cloud Computing, TensorFlow, SQL, ...
Cybersecurity Analyst  Excel, Kubernetes, Prompt Engineering, Leadership
Healthcare Analyst            SQL, Leadership, TensorFlow, Cybersecurity
...                                                                  ...
Data Scientist         Azure, Project Management, Cloud Computing, Cy...
Data Engineer                             Communication, PyTorch, Docker
DevOps Engineer                        TensorFlow, Excel, Python, Docker
Data Scientist             Cybersecurity, Cloud Computing, Deep Learning
HR Specialist                   Kubernetes, Cybersecurity, Communication

                      Automation_Level  Job_Growth_2030  Work_Hours_Per_Week  \
Job_Title
Data Engineer                      Low                3                   37
Healthcare Analyst                 Low               -5                   42
HR Specialist                   Medium               -5                   57
Cybersecurity Analyst           Medium                7                   59
Healthcare Analyst                 Low                6                   34
...                                ...              ...                  ...
Data Scientist                  Medium               36                   59
Data Engineer                      Low               17                   45
DevOps Engineer                 Medium               34                   35
Data Scientist                  Medium               21                   47
HR Specialist                      Low               32                   44

                      Company_Size AI_Tool_Usage  Performance_Score  \
Job_Title
Data Engineer           Enterprise          High               2.08
Healthcare Analyst         Startup      Moderate               4.54
HR Specialist              Startup           Low               3.14
Cybersecurity Analyst   Enterprise          High               3.67
Healthcare Analyst         Startup          High               3.68
...                            ...           ...                ...
Data Scientist          Enterprise      Moderate               4.54
Data Engineer              Startup           Low               2.71
DevOps Engineer            Startup           Low               4.88
Data Scientist             Startup      Moderate               3.59
HR Specialist               Medium      Moderate               3.29

                      Upskilling_Needed  Job_Satisfaction Hiring_Trend_2026
Job_Title
Data Engineer                       Yes              3.86           Growing
Healthcare Analyst                   No              4.23           Growing
HR Specialist                        No              3.54            Stable
Cybersecurity Analyst                No              4.37         Declining
Healthcare Analyst                   No              3.99            Stable
...                                 ...               ...               ...
Data Scientist                      Yes              1.27            Stable
Data Engineer                        No              2.56            Stable
DevOps Engineer                     Yes              3.17         Declining
Data Scientist                      Yes              3.78            Stable
HR Specialist                        No              1.36           Growing

[3000 rows x 19 columns]

In [20]:
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv", header=1)
print(csv_1)

      AIJ-100000              Data Engineer  Healthcare      Japan  \
0     AIJ-100001         Healthcare Analyst      Retail         UK
1     AIJ-100002              HR Specialist   Education     Canada
2     AIJ-100003      Cybersecurity Analyst  Government         UK
3     AIJ-100004         Healthcare Analyst   Education        UAE
4     AIJ-100005  Machine Learning Engineer      Energy      Japan
...          ...                        ...         ...        ...
2994  AIJ-102995             Data Scientist   Education      India
2995  AIJ-102996              Data Engineer  Healthcare        UAE
2996  AIJ-102997            DevOps Engineer      Energy   Pakistan
2997  AIJ-102998             Data Scientist  Government  Australia
2998  AIJ-102999              HR Specialist      Retail    Germany

              PhD   1  0.25  0.78     Yes  207392  \
0        Bachelor  24  0.73  0.33      No  140785
1     High School  21  0.80  0.69     Yes  124800
2        Bachelor   5  0.29  0.94      No  199878
3             PhD  20  0.11  0.92      No  178682
4     High School  12  0.73  0.88      No   70066
...           ...  ..   ...   ...     ...     ...
2994     Bachelor   0  0.62  0.27  Hybrid  202565
2995          PhD   4  0.52  0.57     Yes   37215
2996  High School   7  0.72  0.70      No   55179
2997     Bachelor  19  0.82  0.76  Hybrid  125291
2998       Master   9  0.68  0.44      No  152792

                   Python, Communication, Deep Learning     Low   3  37  \
0     Deep Learning, Azure, Communication, TensorFlo...     Low  -5  42
1     Kubernetes, Cloud Computing, TensorFlow, SQL, ...  Medium  -5  57
2     Excel, Kubernetes, Prompt Engineering, Leadership  Medium   7  59
3            SQL, Leadership, TensorFlow, Cybersecurity     Low   6  34
4     Excel, Deep Learning, Cybersecurity, Communica...    High  19  46
...                                                 ...     ...  ..  ..
2994  Azure, Project Management, Cloud Computing, Cy...  Medium  36  59
2995                     Communication, PyTorch, Docker     Low  17  45
2996                  TensorFlow, Excel, Python, Docker  Medium  34  35
2997      Cybersecurity, Cloud Computing, Deep Learning  Medium  21  47
2998           Kubernetes, Cybersecurity, Communication     Low  32  44

      Enterprise      High  2.08 Yes.1  3.86    Growing
0        Startup  Moderate  4.54    No  4.23    Growing
1        Startup       Low  3.14    No  3.54     Stable
2     Enterprise      High  3.67    No  4.37  Declining
3        Startup      High  3.68    No  3.99     Stable
4         Medium      High  4.58   Yes  3.72  Declining
...          ...       ...   ...   ...   ...        ...
2994  Enterprise  Moderate  4.54   Yes  1.27     Stable
2995     Startup       Low  2.71    No  2.56     Stable
2996     Startup       Low  4.88   Yes  3.17  Declining
2997     Startup  Moderate  3.59   Yes  3.78     Stable
2998      Medium  Moderate  3.29    No  1.36    Growing

[2999 rows x 20 columns]

In [21]:
# change the heading using the 'names' function..
varr=pd.read_csv("D:\\Machine Learning\\text.csv",names=["col1","col2"])
print(varr)

   col1  col2
0     1     2
1     1     3
2     2     4
3     3     6
4     4     7

In [22]:
varr=pd.read_csv("D:\\Machine Learning\\text.csv",header=None, dtype={0:float})
varr.columns=[f'col{i}' for i in range(len(varr.columns))]
print(varr)

   col0  col1
0   1.0     2
1   1.0     3
2   2.0     4
3   3.0     6
4   4.0     7

Pandas Function

In [23]:
# index function give index of the csv file, start, stop, step
import pandas as pd
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv")
csv_1.index

RangeIndex(start=0, stop=3000, step=1)

In [24]:
# Get columns = It give every heading at 0 index
import pandas as pd
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv")
csv_1.columns

Index(['Employee_ID', 'Job_Title', 'Industry', 'Country', 'Education_Level',
       'Years_Experience', 'AI_Replacement_Risk', 'Future_Demand_Score',
       'Remote_Work_Possibility', 'Average_Salary_USD', 'Required_Skills',
       'Automation_Level', 'Job_Growth_2030', 'Work_Hours_Per_Week',
       'Company_Size', 'AI_Tool_Usage', 'Performance_Score',
       'Upskilling_Needed', 'Job_Satisfaction', 'Hiring_Trend_2026'],
      dtype='object')

In [25]:
# describe method  give the mean, median, 25%, 50%, 75% etc and some other value

import pandas as pd
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv")
csv_1.describe

<bound method NDFrame.describe of      Employee_ID              Job_Title    Industry    Country  \
0     AIJ-100000          Data Engineer  Healthcare      Japan
1     AIJ-100001     Healthcare Analyst      Retail         UK
2     AIJ-100002          HR Specialist   Education     Canada
3     AIJ-100003  Cybersecurity Analyst  Government         UK
4     AIJ-100004     Healthcare Analyst   Education        UAE
...          ...                    ...         ...        ...
2995  AIJ-102995         Data Scientist   Education      India
2996  AIJ-102996          Data Engineer  Healthcare        UAE
2997  AIJ-102997        DevOps Engineer      Energy   Pakistan
2998  AIJ-102998         Data Scientist  Government  Australia
2999  AIJ-102999          HR Specialist      Retail    Germany

     Education_Level  Years_Experience  AI_Replacement_Risk  \
0                PhD                 1                 0.25
1           Bachelor                24                 0.73
2        High School                21                 0.80
3           Bachelor                 5                 0.29
4                PhD                20                 0.11
...              ...               ...                  ...
2995        Bachelor                 0                 0.62
2996             PhD                 4                 0.52
2997     High School                 7                 0.72
2998        Bachelor                19                 0.82
2999          Master                 9                 0.68

      Future_Demand_Score Remote_Work_Possibility  Average_Salary_USD  \
0                    0.78                     Yes              207392
1                    0.33                      No              140785
2                    0.69                     Yes              124800
3                    0.94                      No              199878
4                    0.92                      No              178682
...                   ...                     ...                 ...
2995                 0.27                  Hybrid              202565
2996                 0.57                     Yes               37215
2997                 0.70                      No               55179
2998                 0.76                  Hybrid              125291
2999                 0.44                      No              152792

                                        Required_Skills Automation_Level  \
0                  Python, Communication, Deep Learning              Low
1     Deep Learning, Azure, Communication, TensorFlo...              Low
2     Kubernetes, Cloud Computing, TensorFlow, SQL, ...           Medium
3     Excel, Kubernetes, Prompt Engineering, Leadership           Medium
4            SQL, Leadership, TensorFlow, Cybersecurity              Low
...                                                 ...              ...
2995  Azure, Project Management, Cloud Computing, Cy...           Medium
2996                     Communication, PyTorch, Docker              Low
2997                  TensorFlow, Excel, Python, Docker           Medium
2998      Cybersecurity, Cloud Computing, Deep Learning           Medium
2999           Kubernetes, Cybersecurity, Communication              Low

      Job_Growth_2030  Work_Hours_Per_Week Company_Size AI_Tool_Usage  \
0                   3                   37   Enterprise          High
1                  -5                   42      Startup      Moderate
2                  -5                   57      Startup           Low
3                   7                   59   Enterprise          High
4                   6                   34      Startup          High
...               ...                  ...          ...           ...
2995               36                   59   Enterprise      Moderate
2996               17                   45      Startup           Low
2997               34                   35      Startup           Low
2998               21                   47      Startup      Moderate
2999               32                   44       Medium      Moderate

      Performance_Score Upskilling_Needed  Job_Satisfaction Hiring_Trend_2026
0                  2.08               Yes              3.86           Growing
1                  4.54                No              4.23           Growing
2                  3.14                No              3.54            Stable
3                  3.67                No              4.37         Declining
4                  3.68                No              3.99            Stable
...                 ...               ...               ...               ...
2995               4.54               Yes              1.27            Stable
2996               2.71                No              2.56            Stable
2997               4.88               Yes              3.17         Declining
2998               3.59               Yes              3.78            Stable
2999               3.29                No              1.36           Growing

[3000 rows x 20 columns]>

In [26]:
# head method = Give the only few  data from above the csv file 
# get some row according to you choice 

import pandas as pd
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv")
csv_1.head()
csv_1.head(2)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing

In [27]:
# tail method give the last row of the csv file
# get the required row from the bottom of the csv file

import pandas as pd
csv_1=pd.read_csv("D:\\Machine Learning\\AI_Impact_on_Jobs_2030.csv")
csv_1.tail()
csv_1.tail(2)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
2998,AIJ-102998,Data Scientist,Government,Australia,Bachelor,19,0.82,0.76,Hybrid,125291,"Cybersecurity, Cloud Computing, Deep Learning",Medium,21,47,Startup,Moderate,3.59,Yes,3.78,Stable
2999,AIJ-102999,HR Specialist,Retail,Germany,Master,9,0.68,0.44,No,152792,"Kubernetes, Cybersecurity, Communication",Low,32,44,Medium,Moderate,3.29,No,1.36,Growing

In [28]:
# slicing of the data, same as the string 
csv_1[:4]

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing
2,AIJ-100002,HR Specialist,Education,Canada,High School,21,0.80,0.69,Yes,124800,"Kubernetes, Cloud Computing, TensorFlow, SQL, ...",Medium,-5,57,Startup,Low,3.14,No,3.54,Stable
3,AIJ-100003,Cybersecurity Analyst,Government,UK,Bachelor,5,0.29,0.94,No,199878,"Excel, Kubernetes, Prompt Engineering, Leadership",Medium,7,59,Enterprise,High,3.67,No,4.37,Declining

In [29]:
# Store the index into the array
csv_1.index.array

<NumpyExtensionArray>
[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
 ...
 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999]
Length: 3000, dtype: int64

In [30]:
# pandas to numpy
# csv file store in the numpy, mean the nth list 
csv_1.to_numpy()

array([['AIJ-100000', 'Data Engineer', 'Healthcare', ..., 'Yes', 3.86,
        'Growing'],
       ['AIJ-100001', 'Healthcare Analyst', 'Retail', ..., 'No', 4.23,
        'Growing'],
       ['AIJ-100002', 'HR Specialist', 'Education', ..., 'No', 3.54,
        'Stable'],
       ...,
       ['AIJ-102997', 'DevOps Engineer', 'Energy', ..., 'Yes', 3.17,
        'Declining'],
       ['AIJ-102998', 'Data Scientist', 'Government', ..., 'Yes', 3.78,
        'Stable'],
       ['AIJ-102999', 'HR Specialist', 'Retail', ..., 'No', 1.36,
        'Growing']], shape=(3000, 20), dtype=object)

In [31]:
# Another method to convert the pandas to numpy
import numpy as np
v = np.asarray(csv_1)
v

array([['AIJ-100000', 'Data Engineer', 'Healthcare', ..., 'Yes', 3.86,
        'Growing'],
       ['AIJ-100001', 'Healthcare Analyst', 'Retail', ..., 'No', 4.23,
        'Growing'],
       ['AIJ-100002', 'HR Specialist', 'Education', ..., 'No', 3.54,
        'Stable'],
       ...,
       ['AIJ-102997', 'DevOps Engineer', 'Energy', ..., 'Yes', 3.17,
        'Declining'],
       ['AIJ-102998', 'Data Scientist', 'Government', ..., 'Yes', 3.78,
        'Stable'],
       ['AIJ-102999', 'HR Specialist', 'Retail', ..., 'No', 1.36,
        'Growing']], shape=(3000, 20), dtype=object)

In [32]:
# sort the index of the csv file
# axis = 0, means row
# axis = 1, means column

csv_1.sort_index(axis=0, ascending=False)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
2999,AIJ-102999,HR Specialist,Retail,Germany,Master,9,0.68,0.44,No,152792,"Kubernetes, Cybersecurity, Communication",Low,32,44,Medium,Moderate,3.29,No,1.36,Growing
2998,AIJ-102998,Data Scientist,Government,Australia,Bachelor,19,0.82,0.76,Hybrid,125291,"Cybersecurity, Cloud Computing, Deep Learning",Medium,21,47,Startup,Moderate,3.59,Yes,3.78,Stable
2997,AIJ-102997,DevOps Engineer,Energy,Pakistan,High School,7,0.72,0.70,No,55179,"TensorFlow, Excel, Python, Docker",Medium,34,35,Startup,Low,4.88,Yes,3.17,Declining
2996,AIJ-102996,Data Engineer,Healthcare,UAE,PhD,4,0.52,0.57,Yes,37215,"Communication, PyTorch, Docker",Low,17,45,Startup,Low,2.71,No,2.56,Stable
2995,AIJ-102995,Data Scientist,Education,India,Bachelor,0,0.62,0.27,Hybrid,202565,"Azure, Project Management, Cloud Computing, Cy...",Medium,36,59,Enterprise,Moderate,4.54,Yes,1.27,Stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,AIJ-100004,Healthcare Analyst,Education,UAE,PhD,20,0.11,0.92,No,178682,"SQL, Leadership, TensorFlow, Cybersecurity",Low,6,34,Startup,High,3.68,No,3.99,Stable
3,AIJ-100003,Cybersecurity Analyst,Government,UK,Bachelor,5,0.29,0.94,No,199878,"Excel, Kubernetes, Prompt Engineering, Leadership",Medium,7,59,Enterprise,High,3.67,No,4.37,Declining
2,AIJ-100002,HR Specialist,Education,Canada,High School,21,0.80,0.69,Yes,124800,"Kubernetes, Cloud Computing, TensorFlow, SQL, ...",Medium,-5,57,Startup,Low,3.14,No,3.54,Stable
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing

In [33]:
csv_1.head(2)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing

In [34]:
# change any data inside file 
# csv_1.loc[index, column name as string] = changing value
csv_1.loc[2, 'Job_Title']="unknown"

In [35]:
# get particular data
csv_1.loc[[2],["Job_Title"]]

  Job_Title
2   unknown

In [36]:
# get whole column data then do this
csv_1.loc[:,["Job_Title", "Country"]]
csv_1.head(2)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing

In [37]:
# get the whole data from the row
csv_1.loc[[1,2],:]
csv_1.head(2)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
0,AIJ-100000,Data Engineer,Healthcare,Japan,PhD,1,0.25,0.78,Yes,207392,"Python, Communication, Deep Learning",Low,3,37,Enterprise,High,2.08,Yes,3.86,Growing
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing

In [38]:
# iloc method = get the particular value
# csv_1.iloc[row index, column index]
csv_1.iloc[1,2]

'Retail'

In [39]:
# drop method = drop any row 
# csv_1.drop(row index, axis)
csv_1.drop(0,axis=0)

,Employee_ID,Job_Title,Industry,Country,Education_Level,Years_Experience,AI_Replacement_Risk,Future_Demand_Score,Remote_Work_Possibility,Average_Salary_USD,Required_Skills,Automation_Level,Job_Growth_2030,Work_Hours_Per_Week,Company_Size,AI_Tool_Usage,Performance_Score,Upskilling_Needed,Job_Satisfaction,Hiring_Trend_2026
1,AIJ-100001,Healthcare Analyst,Retail,UK,Bachelor,24,0.73,0.33,No,140785,"Deep Learning, Azure, Communication, TensorFlo...",Low,-5,42,Startup,Moderate,4.54,No,4.23,Growing
2,AIJ-100002,unknown,Education,Canada,High School,21,0.80,0.69,Yes,124800,"Kubernetes, Cloud Computing, TensorFlow, SQL, ...",Medium,-5,57,Startup,Low,3.14,No,3.54,Stable
3,AIJ-100003,Cybersecurity Analyst,Government,UK,Bachelor,5,0.29,0.94,No,199878,"Excel, Kubernetes, Prompt Engineering, Leadership",Medium,7,59,Enterprise,High,3.67,No,4.37,Declining
4,AIJ-100004,Healthcare Analyst,Education,UAE,PhD,20,0.11,0.92,No,178682,"SQL, Leadership, TensorFlow, Cybersecurity",Low,6,34,Startup,High,3.68,No,3.99,Stable
5,AIJ-100005,Machine Learning Engineer,Energy,Japan,High School,12,0.73,0.88,No,70066,"Excel, Deep Learning, Cybersecurity, Communica...",High,19,46,Medium,High,4.58,Yes,3.72,Declining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,AIJ-102995,Data Scientist,Education,India,Bachelor,0,0.62,0.27,Hybrid,202565,"Azure, Project Management, Cloud Computing, Cy...",Medium,36,59,Enterprise,Moderate,4.54,Yes,1.27,Stable
2996,AIJ-102996,Data Engineer,Healthcare,UAE,PhD,4,0.52,0.57,Yes,37215,"Communication, PyTorch, Docker",Low,17,45,Startup,Low,2.71,No,2.56,Stable
2997,AIJ-102997,DevOps Engineer,Energy,Pakistan,High School,7,0.72,0.70,No,55179,"TensorFlow, Excel, Python, Docker",Medium,34,35,Startup,Low,4.88,Yes,3.17,Declining
2998,AIJ-102998,Data Scientist,Government,Australia,Bachelor,19,0.82,0.76,Hybrid,125291,"Cybersecurity, Cloud Computing, Deep Learning",Medium,21,47,Startup,Moderate,3.59,Yes,3.78,Stable
2999,AIJ-102999,HR Specialist,Retail,Germany,Master,9,0.68,0.44,No,152792,"Kubernetes, Cybersecurity, Communication",Low,32,44,Medium,Moderate,3.29,No,1.36,Growing

Dropna and Fillna

In [40]:
import pandas as pd
csv_2 = pd.read_csv("D:\\Machine Learning\\incomplete_people_dataset_50.csv")
csv_2.head(15)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0

In [41]:
# dropna = skip the incomplet value
csv_2.dropna(axis=0)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0

In [42]:
# how="any", skip every NaN row if any one of the present..
# how="all", skip only when the how row is NaN
csv_2.dropna(how="any")
csv_2.dropna(how="all")

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [43]:
# skip only particular column NaN v
csv_2.dropna(subset=["Name"])

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [44]:
# skip NaN row, NaN present in any one then skip whole row
csv_2.dropna(inplace=True)
csv_2

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0

In [45]:
# any row have only one NaN the it remove the row  
# if two or more then put and skip the row like this
csv_2.dropna(thresh=1)
csv_2.dropna(thresh=2)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0

In [46]:
# fillna method
import pandas as pd
csv_3 = pd.read_csv("D:\\Machine Learning\\incomplete_people_dataset_50.csv")
csv_3.head(5)

   ID      Name   Age  Gender Job_Title   Salary       City  Experience_Years
0   1  Person_1  21.0  Female   Teacher  26200.0       Pune               1.0
1   2  Person_2  22.0     NaN   Analyst  27400.0      Delhi               2.0
2   3  Person_3  23.0    Male  Designer  28600.0        NaN               3.0
3   4  Person_4  24.0  Female   Manager  29800.0  Bengaluru               4.0
4   5  Person_5  25.0     NaN       NaN  31000.0     Mumbai               5.0

In [47]:
csv_3.fillna("python")

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,python,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,python,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,python,python,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,python,Pune,6.0
6,7,Person_7,python,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,python,Analyst,34600.0,python,python
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,python,31.0,python,python,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,python,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,python,13.0
13,14,Person_14,python,python,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,python
16,17,Person_17,37.0,python,python,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,python,python,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,python,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,python,Male,Designer,50200.0,Pune,6.0
21,22,python,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,python,python,52600.0,python,8.0
23,24,Person_24,44.0,Male,Engineer,python,Bengaluru,python
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,python,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,python,Female,Manager,58600.0,python,13.0
28,29,Person_29,24.0,python,python,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,python,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,python,Analyst,63400.0,Delhi,python
32,33,python,28.0,Male,Designer,64600.0,python,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,python,python,python,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,python,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,python,Analyst,70600.0,python,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,python
40,41,Person_41,36.0,python,python,74200.0,Pune,11.0
41,42,Person_42,python,Male,Engineer,python,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,python,13.0
43,44,python,39.0,python,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,python,python,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,python,python,python
48,49,Person_49,python,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,python,Analyst,85000.0,Mumbai,5.0

In [48]:
# fill multiple value using dictionary
csv_3.fillna({"Name" : "Chitu", "Gender" : "Transgender", "Salary" : "20000"})

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,Transgender,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,Transgender,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,20000,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,Transgender,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,Chitu,31.0,Transgender,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,20000,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,Transgender,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,Transgender,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,20000,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,Transgender,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,Chitu,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,Transgender,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,20000,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,Transgender,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,Transgender,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,20000,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,Transgender,Analyst,63400.0,Delhi,NaN
32,33,Chitu,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,Transgender,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,20000,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,Transgender,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,Transgender,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,20000,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,Chitu,39.0,Transgender,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,Transgender,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,20000,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,Transgender,Analyst,85000.0,Mumbai,5.0

In [49]:
# if you want to fill the forward or backword the do this

csv_3.fillna(method="ffill" ,axis=0) # forward filling 
csv_3.fillna(method="bfill" , axis=1) # backward filling

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\493996008.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_3.fillna(method="ffill" ,axis=0) # forward filling
C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\493996008.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_3.fillna(method="bfill" , axis=1) # backward filling

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,Analyst,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,3.0,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,31000.0,31000.0,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,Pune,Pune,6.0
6,7,Person_7,Female,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,Analyst,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,31.0,31.0,38200.0,38200.0,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,Delhi,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,13.0,13.0
13,14,Person_14,Analyst,Analyst,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,45400.0,45400.0,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,3.0,3.0,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,Analyst,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,Male,Male,Designer,50200.0,Pune,6.0
21,22,42.0,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,52600.0,52600.0,52600.0,8.0,8.0
23,24,Person_24,44.0,Male,Engineer,Bengaluru,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,Analyst,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,Female,Female,Manager,58600.0,13.0,13.0
28,29,Person_29,24.0,59800.0,59800.0,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,Mumbai,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,Analyst,Analyst,63400.0,Delhi,NaN
32,33,28.0,28.0,Male,Designer,64600.0,3.0,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,67000.0,67000.0,67000.0,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,Pune,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,Analyst,Analyst,70600.0,8.0,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,74200.0,74200.0,74200.0,Pune,11.0
41,42,Person_42,Male,Male,Engineer,Delhi,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,13.0,13.0
43,44,39.0,39.0,Analyst,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,81400.0,81400.0,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,Female,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,Analyst,Analyst,85000.0,Mumbai,5.0

In [50]:
csv_3.fillna(12, inplace=True)
csv_3

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,12,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,12,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,12,12,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,12.0,Pune,6.0
6,7,Person_7,12.0,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,12,Analyst,34600.0,12,12.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,12,31.0,12,12,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,12.0,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,12,13.0
13,14,Person_14,12.0,12,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,12.0
16,17,Person_17,37.0,12,12,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,12.0,12,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,12,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,12.0,Male,Designer,50200.0,Pune,6.0
21,22,12,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,12,12,52600.0,12,8.0
23,24,Person_24,44.0,Male,Engineer,12.0,Bengaluru,12.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,12,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,12.0,Female,Manager,58600.0,12,13.0
28,29,Person_29,24.0,12,12,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,12.0,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,12,Analyst,63400.0,Delhi,12.0
32,33,12,28.0,Male,Designer,64600.0,12,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,12.0,12,12,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,12.0,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,12,Analyst,70600.0,12,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,12.0
40,41,Person_41,36.0,12,12,74200.0,Pune,11.0
41,42,Person_42,12.0,Male,Engineer,12.0,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,12,13.0
43,44,12,39.0,12,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,12,12,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,12.0,12,12.0
48,49,Person_49,12.0,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,12,Analyst,85000.0,Mumbai,5.0

In [51]:
# no. of filling data
# csv_3.fillna("what you want to fill", limit=) 
csv_3.fillna("python", limit=2)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,12,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,12,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,12,12,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,12.0,Pune,6.0
6,7,Person_7,12.0,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,12,Analyst,34600.0,12,12.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,12,31.0,12,12,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,12.0,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,12,13.0
13,14,Person_14,12.0,12,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,12.0
16,17,Person_17,37.0,12,12,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,12.0,12,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,12,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,12.0,Male,Designer,50200.0,Pune,6.0
21,22,12,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,12,12,52600.0,12,8.0
23,24,Person_24,44.0,Male,Engineer,12.0,Bengaluru,12.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,12,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,12.0,Female,Manager,58600.0,12,13.0
28,29,Person_29,24.0,12,12,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,12.0,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,12,Analyst,63400.0,Delhi,12.0
32,33,12,28.0,Male,Designer,64600.0,12,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,12.0,12,12,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,12.0,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,12,Analyst,70600.0,12,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,12.0
40,41,Person_41,36.0,12,12,74200.0,Pune,11.0
41,42,Person_42,12.0,Male,Engineer,12.0,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,12,13.0
43,44,12,39.0,12,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,12,12,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,12.0,12,12.0
48,49,Person_49,12.0,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,12,Analyst,85000.0,Mumbai,5.0

Replace

In [52]:
import pandas as pd
csv_4 = pd.read_csv("D:\\Machine Learning\\incomplete_people_dataset_50.csv")
csv_4

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [53]:
# Replace the value
# csv_4.replace(to_replace="which thing you want to replace" , value="which value place as replacement")
# also replace with string ..
csv_4.replace(to_replace=1, value=22)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,22,Person_1,21.0,Female,Teacher,26200.0,Pune,22.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,22.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,22.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [54]:
# replace the index
# csv_4.replace([index, which you want to replace], value)
csv_4.replace([1,2,3,4,5,6],44)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,44,Person_1,21.0,Female,Teacher,26200.0,Pune,44.0
1,44,Person_2,22.0,NaN,Analyst,27400.0,Delhi,44.0
2,44,Person_3,23.0,Male,Designer,28600.0,NaN,44.0
3,44,Person_4,24.0,Female,Manager,29800.0,Bengaluru,44.0
4,44,Person_5,25.0,NaN,NaN,31000.0,Mumbai,44.0
5,44,Person_6,26.0,Male,Engineer,NaN,Pune,44.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,44.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,44.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,44.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,44.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,44.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,44.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,44.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,44.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,44.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,44.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,44.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,44.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,44.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,44.0

In [55]:
# regex = True replace the alphabet like this
# csv_4.replace("[replace]", value, regex=True)
import pandas as pd
csv_4 = pd.read_csv("D:\\Machine Learning\\incomplete_people_dataset_50.csv")
csv_4.replace("[A-Z]", "python", regex = True)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,pythonerson_1,21.0,pythonemale,pythoneacher,26200.0,pythonune,1.0
1,2,pythonerson_2,22.0,NaN,pythonnalyst,27400.0,pythonelhi,2.0
2,3,pythonerson_3,23.0,pythonale,pythonesigner,28600.0,NaN,3.0
3,4,pythonerson_4,24.0,pythonemale,pythonanager,29800.0,pythonengaluru,4.0
4,5,pythonerson_5,25.0,NaN,NaN,31000.0,pythonumbai,5.0
5,6,pythonerson_6,26.0,pythonale,pythonngineer,NaN,pythonune,6.0
6,7,pythonerson_7,NaN,pythonemale,pythoneacher,33400.0,pythonelhi,7.0
7,8,pythonerson_8,28.0,NaN,pythonnalyst,34600.0,NaN,NaN
8,9,pythonerson_9,29.0,pythonale,pythonesigner,35800.0,pythonengaluru,9.0
9,10,pythonerson_10,30.0,pythonemale,pythonanager,37000.0,pythonumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,pythonune,11.0
11,12,pythonerson_12,32.0,pythonale,pythonngineer,NaN,pythonelhi,12.0
12,13,pythonerson_13,33.0,pythonemale,pythoneacher,40600.0,NaN,13.0
13,14,pythonerson_14,NaN,NaN,pythonnalyst,41800.0,pythonengaluru,14.0
14,15,pythonerson_15,35.0,pythonale,pythonesigner,43000.0,pythonumbai,0.0
15,16,pythonerson_16,36.0,pythonemale,pythonanager,44200.0,pythonune,NaN
16,17,pythonerson_17,37.0,NaN,NaN,45400.0,pythonelhi,2.0
17,18,pythonerson_18,38.0,pythonale,pythonngineer,NaN,NaN,3.0
18,19,pythonerson_19,39.0,pythonemale,pythoneacher,47800.0,pythonengaluru,4.0
19,20,pythonerson_20,40.0,NaN,pythonnalyst,49000.0,pythonumbai,5.0
20,21,pythonerson_21,NaN,pythonale,pythonesigner,50200.0,pythonune,6.0
21,22,NaN,42.0,pythonemale,pythonanager,51400.0,pythonelhi,7.0
22,23,pythonerson_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,pythonerson_24,44.0,pythonale,pythonngineer,NaN,pythonengaluru,NaN
24,25,pythonerson_25,20.0,pythonemale,pythoneacher,55000.0,pythonumbai,10.0
25,26,pythonerson_26,21.0,NaN,pythonnalyst,56200.0,pythonune,11.0
26,27,pythonerson_27,22.0,pythonale,pythonesigner,57400.0,pythonelhi,12.0
27,28,pythonerson_28,NaN,pythonemale,pythonanager,58600.0,NaN,13.0
28,29,pythonerson_29,24.0,NaN,NaN,59800.0,pythonengaluru,14.0
29,30,pythonerson_30,25.0,pythonale,pythonngineer,NaN,pythonumbai,0.0
30,31,pythonerson_31,26.0,pythonemale,pythoneacher,62200.0,pythonune,1.0
31,32,pythonerson_32,27.0,NaN,pythonnalyst,63400.0,pythonelhi,NaN
32,33,NaN,28.0,pythonale,pythonesigner,64600.0,NaN,3.0
33,34,pythonerson_34,29.0,pythonemale,pythonanager,65800.0,pythonengaluru,4.0
34,35,pythonerson_35,NaN,NaN,NaN,67000.0,pythonumbai,5.0
35,36,pythonerson_36,31.0,pythonale,pythonngineer,NaN,pythonune,6.0
36,37,pythonerson_37,32.0,pythonemale,pythoneacher,69400.0,pythonelhi,7.0
37,38,pythonerson_38,33.0,NaN,pythonnalyst,70600.0,NaN,8.0
38,39,pythonerson_39,34.0,pythonale,pythonesigner,71800.0,pythonengaluru,9.0
39,40,pythonerson_40,35.0,pythonemale,pythonanager,73000.0,pythonumbai,NaN
40,41,pythonerson_41,36.0,NaN,NaN,74200.0,pythonune,11.0
41,42,pythonerson_42,NaN,pythonale,pythonngineer,NaN,pythonelhi,12.0
42,43,pythonerson_43,38.0,pythonemale,pythoneacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,pythonnalyst,77800.0,pythonengaluru,14.0
44,45,pythonerson_45,40.0,pythonale,pythonesigner,79000.0,pythonumbai,0.0
45,46,pythonerson_46,41.0,pythonemale,pythonanager,80200.0,pythonune,1.0
46,47,pythonerson_47,42.0,NaN,NaN,81400.0,pythonelhi,2.0
47,48,pythonerson_48,43.0,pythonale,pythonngineer,NaN,NaN,NaN
48,49,pythonerson_49,NaN,pythonemale,pythoneacher,83800.0,pythonengaluru,4.0
49,50,pythonerson_50,20.0,NaN,pythonnalyst,85000.0,pythonumbai,5.0

In [56]:
# using dictionary for particular column replacement
csv_4.replace({"Name" : '[A-Z]'}, 25, regex=True)

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\1267625595.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  csv_4.replace({"Name" : '[A-Z]'}, 25, regex=True)

    ID  Name   Age  Gender Job_Title   Salary       City  Experience_Years
0    1  25.0  21.0  Female   Teacher  26200.0       Pune               1.0
1    2  25.0  22.0     NaN   Analyst  27400.0      Delhi               2.0
2    3  25.0  23.0    Male  Designer  28600.0        NaN               3.0
3    4  25.0  24.0  Female   Manager  29800.0  Bengaluru               4.0
4    5  25.0  25.0     NaN       NaN  31000.0     Mumbai               5.0
5    6  25.0  26.0    Male  Engineer      NaN       Pune               6.0
6    7  25.0   NaN  Female   Teacher  33400.0      Delhi               7.0
7    8  25.0  28.0     NaN   Analyst  34600.0        NaN               NaN
8    9  25.0  29.0    Male  Designer  35800.0  Bengaluru               9.0
9   10  25.0  30.0  Female   Manager  37000.0     Mumbai              10.0
10  11   NaN  31.0     NaN       NaN  38200.0       Pune              11.0
11  12  25.0  32.0    Male  Engineer      NaN      Delhi              12.0
12  13  25.0  33.0  Female   Teacher  40600.0        NaN              13.0
13  14  25.0   NaN     NaN   Analyst  41800.0  Bengaluru              14.0
14  15  25.0  35.0    Male  Designer  43000.0     Mumbai               0.0
15  16  25.0  36.0  Female   Manager  44200.0       Pune               NaN
16  17  25.0  37.0     NaN       NaN  45400.0      Delhi               2.0
17  18  25.0  38.0    Male  Engineer      NaN        NaN               3.0
18  19  25.0  39.0  Female   Teacher  47800.0  Bengaluru               4.0
19  20  25.0  40.0     NaN   Analyst  49000.0     Mumbai               5.0
20  21  25.0   NaN    Male  Designer  50200.0       Pune               6.0
21  22   NaN  42.0  Female   Manager  51400.0      Delhi               7.0
22  23  25.0  43.0     NaN       NaN  52600.0        NaN               8.0
23  24  25.0  44.0    Male  Engineer      NaN  Bengaluru               NaN
24  25  25.0  20.0  Female   Teacher  55000.0     Mumbai              10.0
25  26  25.0  21.0     NaN   Analyst  56200.0       Pune              11.0
26  27  25.0  22.0    Male  Designer  57400.0      Delhi              12.0
27  28  25.0   NaN  Female   Manager  58600.0        NaN              13.0
28  29  25.0  24.0     NaN       NaN  59800.0  Bengaluru              14.0
29  30  25.0  25.0    Male  Engineer      NaN     Mumbai               0.0
30  31  25.0  26.0  Female   Teacher  62200.0       Pune               1.0
31  32  25.0  27.0     NaN   Analyst  63400.0      Delhi               NaN
32  33   NaN  28.0    Male  Designer  64600.0        NaN               3.0
33  34  25.0  29.0  Female   Manager  65800.0  Bengaluru               4.0
34  35  25.0   NaN     NaN       NaN  67000.0     Mumbai               5.0
35  36  25.0  31.0    Male  Engineer      NaN       Pune               6.0
36  37  25.0  32.0  Female   Teacher  69400.0      Delhi               7.0
37  38  25.0  33.0     NaN   Analyst  70600.0        NaN               8.0
38  39  25.0  34.0    Male  Designer  71800.0  Bengaluru               9.0
39  40  25.0  35.0  Female   Manager  73000.0     Mumbai               NaN
40  41  25.0  36.0     NaN       NaN  74200.0       Pune              11.0
41  42  25.0   NaN    Male  Engineer      NaN      Delhi              12.0
42  43  25.0  38.0  Female   Teacher  76600.0        NaN              13.0
43  44   NaN  39.0     NaN   Analyst  77800.0  Bengaluru              14.0
44  45  25.0  40.0    Male  Designer  79000.0     Mumbai               0.0
45  46  25.0  41.0  Female   Manager  80200.0       Pune               1.0
46  47  25.0  42.0     NaN       NaN  81400.0      Delhi               2.0
47  48  25.0  43.0    Male  Engineer      NaN        NaN               NaN
48  49  25.0   NaN  Female   Teacher  83800.0  Bengaluru               4.0
49  50  25.0  20.0     NaN   Analyst  85000.0     Mumbai               5.0

In [57]:
# csv_4.replace(which item replace, method=forward or backword filling)
csv_4.replace(1, method="ffill") # forward filling 
csv_4.replace(1, method="bfill")  # backward filling

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\1981458634.py:2: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_4.replace(1, method="ffill") # forward filling
C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\1981458634.py:3: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_4.replace(1, method="bfill")  # backward filling

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,2,Person_1,21.0,Female,Teacher,26200.0,Pune,2.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,NaN
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,2.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [58]:
# limited amount of data replace
csv_4.replace(1, method="bfill", limit=1)
csv_4

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\3195671204.py:2: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_4.replace(1, method="bfill", limit=1)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [59]:
# inplace method change the original value 
csv_4.replace(1, method="bfill", limit=1, inplace=True)
csv_4

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\3190819081.py:2: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_4.replace(1, method="bfill", limit=1, inplace=True)

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,2,Person_1,21.0,Female,Teacher,26200.0,Pune,2.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,NaN
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,2.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

Interpolate Method....

In [60]:
# interpolate method = fill the empty space
import pandas as pd
csv_5 = pd.read_csv("D:\\Machine Learning\\incomplete_people_dataset_50.csv")
csv_5

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,NaN,Pune,6.0
6,7,Person_7,NaN,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,NaN
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,NaN,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,NaN,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,NaN
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,NaN,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,NaN,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,NaN,Bengaluru,NaN
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,NaN,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,NaN,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,NaN
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,NaN,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,NaN,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,NaN
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,NaN,Male,Engineer,NaN,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,NaN,NaN,NaN
48,49,Person_49,NaN,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [61]:
csv_5.interpolate()

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\1368387926.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_5.interpolate()

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,32200.0,Pune,6.0
6,7,Person_7,27.0,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,8.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,39400.0,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,34.0,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,1.0
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,46600.0,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,41.0,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,53800.0,Bengaluru,9.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,23.0,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,61000.0,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,2.0
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,30.0,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,68200.0,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,10.0
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,37.0,Male,Engineer,75400.0,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,82600.0,NaN,3.0
48,49,Person_49,31.5,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [62]:
# fill the data linear
csv_5.interpolate(method="linear")

C:\Users\vikra\AppData\Local\Temp\ipykernel_17532\4216232676.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_5.interpolate(method="linear")

,ID,Name,Age,Gender,Job_Title,Salary,City,Experience_Years
0,1,Person_1,21.0,Female,Teacher,26200.0,Pune,1.0
1,2,Person_2,22.0,NaN,Analyst,27400.0,Delhi,2.0
2,3,Person_3,23.0,Male,Designer,28600.0,NaN,3.0
3,4,Person_4,24.0,Female,Manager,29800.0,Bengaluru,4.0
4,5,Person_5,25.0,NaN,NaN,31000.0,Mumbai,5.0
5,6,Person_6,26.0,Male,Engineer,32200.0,Pune,6.0
6,7,Person_7,27.0,Female,Teacher,33400.0,Delhi,7.0
7,8,Person_8,28.0,NaN,Analyst,34600.0,NaN,8.0
8,9,Person_9,29.0,Male,Designer,35800.0,Bengaluru,9.0
9,10,Person_10,30.0,Female,Manager,37000.0,Mumbai,10.0
10,11,NaN,31.0,NaN,NaN,38200.0,Pune,11.0
11,12,Person_12,32.0,Male,Engineer,39400.0,Delhi,12.0
12,13,Person_13,33.0,Female,Teacher,40600.0,NaN,13.0
13,14,Person_14,34.0,NaN,Analyst,41800.0,Bengaluru,14.0
14,15,Person_15,35.0,Male,Designer,43000.0,Mumbai,0.0
15,16,Person_16,36.0,Female,Manager,44200.0,Pune,1.0
16,17,Person_17,37.0,NaN,NaN,45400.0,Delhi,2.0
17,18,Person_18,38.0,Male,Engineer,46600.0,NaN,3.0
18,19,Person_19,39.0,Female,Teacher,47800.0,Bengaluru,4.0
19,20,Person_20,40.0,NaN,Analyst,49000.0,Mumbai,5.0
20,21,Person_21,41.0,Male,Designer,50200.0,Pune,6.0
21,22,NaN,42.0,Female,Manager,51400.0,Delhi,7.0
22,23,Person_23,43.0,NaN,NaN,52600.0,NaN,8.0
23,24,Person_24,44.0,Male,Engineer,53800.0,Bengaluru,9.0
24,25,Person_25,20.0,Female,Teacher,55000.0,Mumbai,10.0
25,26,Person_26,21.0,NaN,Analyst,56200.0,Pune,11.0
26,27,Person_27,22.0,Male,Designer,57400.0,Delhi,12.0
27,28,Person_28,23.0,Female,Manager,58600.0,NaN,13.0
28,29,Person_29,24.0,NaN,NaN,59800.0,Bengaluru,14.0
29,30,Person_30,25.0,Male,Engineer,61000.0,Mumbai,0.0
30,31,Person_31,26.0,Female,Teacher,62200.0,Pune,1.0
31,32,Person_32,27.0,NaN,Analyst,63400.0,Delhi,2.0
32,33,NaN,28.0,Male,Designer,64600.0,NaN,3.0
33,34,Person_34,29.0,Female,Manager,65800.0,Bengaluru,4.0
34,35,Person_35,30.0,NaN,NaN,67000.0,Mumbai,5.0
35,36,Person_36,31.0,Male,Engineer,68200.0,Pune,6.0
36,37,Person_37,32.0,Female,Teacher,69400.0,Delhi,7.0
37,38,Person_38,33.0,NaN,Analyst,70600.0,NaN,8.0
38,39,Person_39,34.0,Male,Designer,71800.0,Bengaluru,9.0
39,40,Person_40,35.0,Female,Manager,73000.0,Mumbai,10.0
40,41,Person_41,36.0,NaN,NaN,74200.0,Pune,11.0
41,42,Person_42,37.0,Male,Engineer,75400.0,Delhi,12.0
42,43,Person_43,38.0,Female,Teacher,76600.0,NaN,13.0
43,44,NaN,39.0,NaN,Analyst,77800.0,Bengaluru,14.0
44,45,Person_45,40.0,Male,Designer,79000.0,Mumbai,0.0
45,46,Person_46,41.0,Female,Manager,80200.0,Pune,1.0
46,47,Person_47,42.0,NaN,NaN,81400.0,Delhi,2.0
47,48,Person_48,43.0,Male,Engineer,82600.0,NaN,3.0
48,49,Person_49,31.5,Female,Teacher,83800.0,Bengaluru,4.0
49,50,Person_50,20.0,NaN,Analyst,85000.0,Mumbai,5.0

In [63]:
# along axis
csv_5.interpolate(method="linear", axis=1)

TypeError: Cannot interpolate with all object-dtype columns in the DataFrame. Try setting at least one column to a numeric dtype.

In [ ]:
csv_5.interpolate(method="linear",axis=0)

In [ ]:
# limited data fill
csv_5.interpolate(limit=2)

In [ ]:
# limited data filling with the direction
csv_5.interpolate(limit_direction="forward", limit=2) # upper side filling
csv_5.interpolate(limit_direction="backward" , limit=3) # downward side filling
csv_5.interpolate(limit_direction="both" , limit=3) # both side upper side and downward side filling

NaN   2   NaN   4   NaN   (limit_area = "inside")
      ↑    ↑    ↑
      Filled only here

NaN   2   NaN   4   NaN  (limit_area = "outside")
 ↑                 ↑
Outside values

In [ ]:
csv_5.interpolate(limit_area="outside", limit=2)
csv_5.interpolate(limit_area="inside")

In [ ]:
csv_5.interpolate(limit_area="outside", limit=2, inplace=True) # modify the original data
csv_5.interpolate(limit_area="outside", limit=2, inplace=False) # Make the copy of the original data

# Merge..

In [ ]:
# it gives output only the common part
# two or more common part merge into sigle part
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "C" : [90,49,39,23,32]})
pd.merge(var1,var2, on="A") # without on="A" it work same as on="A" method

   A    B   C
0  1    3  90
1  2    4  49
2  3    5  39
3  4  676  23

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "C" : [90,49,39,23,32]})
pd.merge(var1,var2, how="inner") # it is same as the normal
pd.merge(var1, var2, how="left")   # left side data output
pd.merge(var1, var2, how="right")  # right side data output
pd.merge(var1, var2, how="outer" , indicator=True)  # both data 

# indicator=True (give the which data is merge or which side merge)

   A      B     C      _merge
0  1    3.0  90.0        both
1  2    4.0  49.0        both
2  3    5.0  39.0        both
3  4  676.0  23.0        both
4  5    5.0   NaN   left_only
5  9    NaN  32.0  right_only

In [ ]:
# get data separatly then do this 
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "C" : [90,49,39,23,32]})
pd.merge(var1,var2, left_index=True, right_index=True)

   A_x    B  A_y   C
0    1    3    1  90
1    2    4    2  49
2    3    5    3  39
3    4  676    4  23
4    5    5    9  32

In [ ]:
# change the column name .
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "C" : [90,49,39,23,32]})
pd.merge(var1,var2, left_index=True, right_index=True, suffixes=("name","python"))

   Aname    B  Apython   C
0      1    3        1  90
1      2    4        2  49
2      3    5        3  39
3      4  676        4  23
4      5    5        9  32

# Concatenation

In [ ]:
import pandas as pd

sr1=pd.Series([1,2,3,4])
sr2=pd.Series([11,21,31,41])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    21
2    31
3    41
dtype: int64

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "B" : [90,49,39,23,32]})
pd.concat([var1,var2], axis=1) # along column
pd.concat([var1,var2], axis=0) # along row

   A    B
0  1    3
1  2    4
2  3    5
3  4  676
4  5    5
0  1   90
1  2   49
2  3   39
3  4   23
4  9   32

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3], "B" : [90,49,39]})
pd.concat([var1,var2],join="outer",axis=1)
pd.concat([var1,var2],join="inner",axis=1)

   A  B  A   B
0  1  3  1  90
1  2  4  2  49
2  3  5  3  39

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "C" : [90,49,39,23,32]})
pd.concat([var1,var2], axis=0,keys=["d1","d2"])
pd.concat([var1,var2], axis=1,keys=["d1","d2"])

  d1      d2
   A    B  A   C
0  1    3  1  90
1  2    4  2  49
2  3    5  3  39
3  4  676  4  23
4  5    5  9  32

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5]})
var2 = pd.DataFrame({"A" : [1,2,3,4,9], "C" : [90,49,39,23,32]})
pd.concat([var1,var2])

   A     C
0  1   NaN
1  2   NaN
2  3   NaN
3  4   NaN
4  5   NaN
0  1  90.0
1  2  49.0
2  3  39.0
3  4  23.0
4  9  32.0

# join

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]}, index=["a","b","c","d","e"])
var2 = pd.DataFrame({"C" : [21,12,23,49], "D" : [90,49,39,32]},index=["a","b","c","d"])
var1.join(var2)

   A    B     C     D
a  1    3  21.0  90.0
b  2    4  12.0  49.0
c  3    5  23.0  39.0
d  4  676  49.0  32.0
e  5    5   NaN   NaN

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]}, index=["a","b","c","d","e"])
var2 = pd.DataFrame({"C" : [21,12,23,49], "D" : [90,49,39,32]},index=["a","b","c","d"])
var2.join(var1)        # it gives ouput according to the var2 DataFrame
var2.join(var1, how="left")    # left side
var2.join(var1, how="right")   # right side
var2.join(var1, how="outer")   # Gives both Union
var2.join(var1, how="inner")   # Gives common data

    C   D  A    B
a  21  90  1    3
b  12  49  2    4
c  23  39  3    5
d  49  32  4  676

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]}, index=["a","b","c","d","e"])
var2 = pd.DataFrame({"C" : [21,12,23,49], "B" : [90,49,39,32]},index=["a","b","c","d"])
var1.join(var2)

ValueError: columns overlap but no suffix specified: Index(['B'], dtype='object')

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]}, index=["a","b","c","d","e"])
var2 = pd.DataFrame({"C" : [21,12,23,49], "B" : [90,49,39,32]},index=["a","b","c","d"])
var1.join(var2,lsuffix="_12", how="outer",rsuffix="_22")
# lsuffix = left side column add something so name is different
# rsuffix = right side same as the lsuffix

   A  B_12     C  B_22
a  1     3  21.0  90.0
b  2     4  12.0  49.0
c  3     5  23.0  39.0
d  4   676  49.0  32.0
e  5     5   NaN   NaN

# Append

In [ ]:
import pandas as pd

var1 = pd.DataFrame({"A" : [1,2,3,4,5], "B" : [3,4,5,676,5]})
var2 = pd.DataFrame({"C" : [21,12,23,49], "B" : [90,49,39,32]})
var1.append(var2)

AttributeError: 'DataFrame' object has no attribute 'append'

# Group by
## arrange the random data into the particular order

In [ ]:
import pandas as pd
var = pd.DataFrame({"name" : ["a", "b","c","d","a","b","a","b","a","c","c","d"],
"s_1" :[12,13,14,15,16,17,18,19,20,21,22,45],
"s_2" :[45,65,23,34,78,67,23,78,23,27,97,89]
})
var

   name  s_1  s_2
0     a   12   45
1     b   13   65
2     c   14   23
3     d   15   34
4     a   16   78
5     b   17   67
6     a   18   23
7     b   19   78
8     a   20   23
9     c   21   27
10    c   22   97
11    d   45   89

In [ ]:
var_New = var.groupby("name")
var_New

In [ ]:
for x ,  y in var_New:
    print(x)
    print(y)
    print()

a
  name  s_1  s_2
0    a   12   45
4    a   16   78
6    a   18   23
8    a   20   23

b
  name  s_1  s_2
1    b   13   65
5    b   17   67
7    b   19   78

c
   name  s_1  s_2
2     c   14   23
9     c   21   27
10    c   22   97

d
   name  s_1  s_2
3     d   15   34
11    d   45   89

In [ ]:
# It give particular data
var_New.get_group("a") # b, c, d put and get

  name  s_1  s_2
0    a   12   45
4    a   16   78
6    a   18   23
8    a   20   23

In [ ]:
# get the minimum value
var_New.min() 
var_New.max()

      s_1  s_2
name
a      12   23
b      13   65
c      14   23
d      15   34

In [ ]:
# convert into the list function
li=list(var_New)
li

[('a',
    name  s_1  s_2
  0    a   12   45
  4    a   16   78
  6    a   18   23
  8    a   20   23),
 ('b',
    name  s_1  s_2
  1    b   13   65
  5    b   17   67
  7    b   19   78),
 ('c',
     name  s_1  s_2
  2     c   14   23
  9     c   21   27
  10    c   22   97),
 ('d',
     name  s_1  s_2
  3     d   15   34
  11    d   45   89)]

# Pivot Table and Melt Function = it help reshape the pandas file

# Melt Function

In [ ]:
# melt function covert horizontal to vartical like this
import pandas as pd
var1 = pd.DataFrame({"days":[1,1,1,1,2,2],
"eng":[10,12,13,14,15,19],
"math":[23,14,56,56,67,65]
})
var1
pd.melt(var1)

   variable  value
0      days      1
1      days      1
2      days      1
3      days      1
4      days      2
5      days      2
6       eng     10
7       eng     12
8       eng     13
9       eng     14
10      eng     15
11      eng     19
12     math     23
13     math     14
14     math     56
15     math     56
16     math     67
17     math     65

In [ ]:
pd.melt(var1,id_vars=["eng"]) # convert eng as id
pd.melt(var1,id_vars=["eng"],var_name="python", value_name="number") # change the variable name

    eng python  number
0    10   days       1
1    12   days       2
2    13   days       3
3    14   days       4
4    15   days       5
5    19   days       6
6    10   math      23
7    12   math      14
8    13   math      56
9    14   math      56
10   15   math      67
11   19   math      65

# Pivot Function = reshaping

In [ ]:
import pandas as pd
var1 = pd.DataFrame({"days":[1,1,1,1,5,6],
"st_name":["a","b","c","a","b","c"],
"eng":[10,12,13,14,15,19],
"math":[23,14,56,56,67,65]
})
var1

   days st_name  eng  math
0     1       a   10    23
1     1       b   12    14
2     1       c   13    56
3     1       a   14    56
4     5       b   15    67
5     6       c   19    65

In [ ]:
var1.pivot(index="days", columns="st_name")

          eng              math
st_name     a     b     c     a     b     c
days
1        10.0   NaN   NaN  23.0   NaN   NaN
2         NaN  12.0   NaN   NaN  14.0   NaN
3         NaN   NaN  13.0   NaN   NaN  56.0
4        14.0   NaN   NaN  56.0   NaN   NaN
5         NaN  15.0   NaN   NaN  67.0   NaN
6         NaN   NaN  19.0   NaN   NaN  65.0

In [ ]:
# get particular subject data then 
var1.pivot(index="days", columns="st_name", values="eng")

st_name     a     b     c
days
1        10.0   NaN   NaN
2         NaN  12.0   NaN
3         NaN   NaN  13.0
4        14.0   NaN   NaN
5         NaN  15.0   NaN
6         NaN   NaN  19.0

In [ ]:
# pivot_table() perform the Arithmatic operation
var1.pivot_table(index="st_name", columns="days", aggfunc="mean") # do sum, median etc

          eng              math
days        1     5     6     1     5     6
st_name
a        12.0   NaN   NaN  39.5   NaN   NaN
b        12.0  15.0   NaN  14.0  67.0   NaN
c        13.0   NaN  19.0  56.0   NaN  65.0

In [ ]:
# margin by default give the mean
var1.pivot_table(index="st_name", columns="days",margins=True)

           eng                          math
days         1     5     6        All      1     5     6        All
st_name
a        12.00   NaN   NaN  12.000000  39.50   NaN   NaN  39.500000
b        12.00  15.0   NaN  13.500000  14.00  67.0   NaN  40.500000
c        13.00   NaN  19.0  16.000000  56.00   NaN  65.0  60.500000
All      12.25  15.0  19.0  13.833333  37.25  67.0  65.0  46.833333