<a href="https://colab.research.google.com/github/vikrampal12345/Pandas-Full-course/blob/main/Pandas_Merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Merge on Single Column

Write a Pandas program to merge two DataFrames on a single column.

In [ ]:
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Age': [25, 30, 22]
})

pd.merge(df1, df2, on='ID' )

   ID     Name  Age
0   2  Annabel   25
1   3    Caeso   30

In [ ]:
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Age': [25, 30, 22]
})

In [ ]:
df1

   ID     Name
0   1   Selena
1   2  Annabel
2   3    Caeso

In [ ]:
df2

   ID  Age
0   2   25
1   3   30
2   4   22

# 2. Outer Join Merge

Write a Pandas program to perform an outer join on two DataFrames.

In [ ]:
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Age': [25, 30, 22]
})

pd.merge(df1, df2, on='ID', how='outer')   # combine all the columns if missing values then it fill by NaN

   ID     Name   Age
0   1   Selena   NaN
1   2  Annabel  25.0
2   3    Caeso  30.0
3   4      NaN  22.0


# 3. Left Join Merge

Write a Pandas program that performs a left join of two DataFrames.

In [ ]:
# it join along Left dataframe if available in right with respect left then merge, not then skip the row
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Age': [25, 30, 22]
})

pd.merge(df1, df2, on='ID', how= 'left')

   ID     Name   Age
0   1   Selena   NaN
1   2  Annabel  25.0
2   3    Caeso  30.0


# 4. Right Join Merge

Write a Pandas program that performs a right join of two DataFrames.

In [ ]:
# it join along Left dataframe if available in right with respect left then merge, not then skip the row
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'Age': [25, 30, 22]
})

pd.merge(df1, df2, on='ID', how=)

# 5. Merge on Multiple Columns

Write a Pandas program to merge two DataFrames on multiple columns.

In [ ]:
import pandas as pd

# Create two sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Age': [25, 30, 22]
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Salary': [50000, 60000, 70000]
})



pd.merge(df1, df2, on=['ID', 'Name'])  # merge along the both the columns

   ID     Name  Age  Salary
0   1   Selena   25   50000
1   2  Annabel   30   60000
2   3    Caeso   22   70000

# 6. Merge Overlapping Columns

Write a Pandas program that merges DataFrames with overlapping column names.

In [ ]:
import pandas as pd

# Create two sample DataFrames with overlapping column names
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Value': [100, 200, 300]
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Value': [400, 500, 600]
})

pd.merge(df1, df2, on=['ID', 'Name'], suffixes=('first', 'seconde'))  # suffix help when the same column name but different value

   ID     Name  Valuefirst  Valueseconde
0   1   Selena         100           400
1   2  Annabel         200           500
2   3    Caeso         300           600


# 7. Merge on Index

Write a Pandas program to merge two DataFrames on their indexes.

In [ ]:
import pandas as pd

# Create two sample DataFrames with indexes
df1 = pd.DataFrame({
    'Name': ['Selena', 'Annabel', 'Caeso'],
    'Age': [25, 30, 22]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'Salary': [50000, 60000, 70000]
}, index=[1, 3, 2])

pd.merge(df1, df2, left_index = True, right_index = True)

# left_index = True means, it allow the left index
# right_index = True mean, it allow the right index
# if both indexes are the same then merge if not then it show the MergeError

      Name  Age  Salary
1   Selena   25   50000
2  Annabel   30   70000
3    Caeso   22   60000

# 8. Merge Diff Column Names

Write a Pandas program to merge different column names in DataFrames.

In [ ]:
import pandas as pd

# Create two sample DataFrames with different join column names
df1 = pd.DataFrame({
    'Employee_ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [1, 3, 2],   # change the sequence but atomatically fix
    'Salary': [50000, 60000, 70000]
})

pd.merge(df1, df2, left_on = 'Employee_ID', right_on = 'ID')

   Employee_ID     Name  ID  Salary
0            1   Selena   1   50000
1            2  Annabel   2   70000
2            3    Caeso   3   60000


# 9. Merge Duplicate Keys

Write a Pandas program to merge DataFrames with duplicate Keys.

In [ ]:
import pandas as pd

# Create two sample DataFrames with duplicate keys
df1 = pd.DataFrame({
    'ID': [1, 1, 2],
    'Name': ['Annabel', 'Annabel', 'Selena']
})

df2 = pd.DataFrame({
    'ID': [1, 2],
    'Age': [25, 30]
})

# Merge the DataFrames with duplicate keys
merged_df = pd.merge(df1, df2, on='ID')

# Output the result
print(merged_df)

   ID     Name  Age
0   1  Annabel   25
1   1  Annabel   25
2   2   Selena   30

# 10. Merge Multiple DataFrames

Write a Pandas program to merge multiple DataFrames on a common column.

In [ ]:

import pandas as pd

# Create three sample DataFrames
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Selena', 'Annabel', 'Caeso']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Age': [25, 30, 22]
})

df3 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Salary': [50000, 60000, 70000]
})

pd.merge(pd.merge(df1, df2, on="ID"), df3, on="ID")

   ID     Name  Age  Salary
0   1   Selena   25   50000
1   2  Annabel   30   60000
2   3    Caeso   22   70000